[build]
  command = "npx prisma generate && npm run build"
  publish = ".next"

[build.environment]
  NEXT_TELEMETRY_DISABLED = "1"
  SECRETS_SCAN_OMIT_KEYS = "NEXT_PUBLIC_BASE_URL"

[[plugins]]
  package = "@netlify/plugin-nextjs"
