// Survey data — question definitions with routing rules.
// Routing based on Q1: reg/occ → actif | ex → ancien | curious/never → non-utilisateur
// Part visibility:
//   1: all
//   2: actif + ancien (adoption)
//   3: actif only (usage)
//   4: all
//   5: actif + ancien (social)
//   6: non-utilisateur only (perception)
//   7: all
//   8: all
export const SURVEY = {
  parts: [
    {
      id: 1, shows: ["reg", "occ", "ex", "curious", "never", "skip"],
      questions: [
        {
          id: "Q2", kind: "multi", key: "discovChannels",
          fr: "Comment avez-vous découvert les gyroroues ?",
          en: "How did you discover electric unicycles?",
          ru: "Как вы узнали об электрических моноколёсах?",
          zh: "您是如何了解到电动独轮车的？",
          hint_fr: "Plusieurs réponses possibles", hint_en: "Select all that apply",
          hint_ru: "Выберите все подходящие варианты", hint_zh: "请选择所有适用项",
          opts_fr: ["Ami", "Vidéo YouTube", "Réseaux sociaux", "En voyant quelqu'un rouler", "Forum internet", "Magasin", "Médias (presse, TV, articles)", "Autre", "Je préfère ne pas répondre"],
          opts_en: ["Friend", "YouTube video", "Social media", "Seeing someone ride", "Internet forum", "Store", "Media (press, TV, articles)", "Other", "Prefer not to say"],
          opts_ru: ["Друг", "Видео на YouTube", "Социальные сети", "Увидел(а) кого-то на моноколесе", "Интернет-форум", "Магазин", "СМИ (пресса, ТВ, статьи)", "Другое", "Я предпочитаю не отвечать"],
          opts_zh: ["朋友", "YouTube视频", "社交媒体", "看到有人在骑", "网络论坛", "商店", "媒体（新闻、电视、文章）", "其他", "我不想说"],
        },
        {
          id: "Q3", kind: "single", key: "socialExposure",
          fr: "Connaissiez-vous quelqu'un qui possédait une gyroroue avant d'en avoir une ?",
          en: "Did you know someone who owned an EUC before you got one?",
          ru: "Знали ли вы кого-то, у кого было моноколесо, до того как приобрели своё?",
          zh: "在您拥有电动独轮车之前，您是否认识拥有它的人？",
          opts_fr: ["Oui", "Non", "Je préfère ne pas répondre"],
          opts_en: ["Yes", "No", "Prefer not to say"],
          opts_ru: ["Да", "Нет", "Я предпочитаю не отвечать"],
          opts_zh: ["是", "否", "我不想说"],
        },
      ],
    },
    {
      id: 2, shows: ["reg", "occ", "ex"],
      questions: [
        {
          id: "Q4", kind: "year", key: "adoptYear",
          fr: "Quand avez-vous acheté votre première gyroroue ?",
          en: "When did you buy your first EUC?",
          ru: "Когда вы купили своё первое моноколесо?",
          zh: "您是什么时候购买第一辆电动独轮车的？",
          placeholder_fr: "Année", placeholder_en: "Year", placeholder_ru: "Год", placeholder_zh: "年份",
        },
        {
          id: "Q5", kind: "single", key: "acquisitionMode",
          fr: "Comment avez-vous acquis votre première gyroroue ?",
          en: "How did you acquire your first EUC?",
          ru: "Как вы приобрели своё первое моноколесо?",
          zh: "您是如何获得第一辆电动独轮车的？",
          opts_fr: ["Achetée neuve", "Achetée d'occasion", "Cadeau", "Prêt ou don", "Autre", "Je préfère ne pas répondre"],
          opts_en: ["Bought new", "Bought used", "Gift", "Loan or donation", "Other", "Prefer not to say"],
          opts_ru: ["Купил(а) новое", "Купил(а) подержанное", "Подарок", "Одолжили или подарили", "Другое", "Я предпочитаю не отвечать"],
          opts_zh: ["购买全新", "购买二手", "礼物", "借用或赠送", "其他", "我不想说"],
        },
        {
          id: "Q6", kind: "single", key: "priceCat",
          fr: "Quel était le prix approximatif de votre première roue ?",
          en: "Approximate price of your first EUC?",
          ru: "Примерная цена вашего первого моноколеса?",
          zh: "您第一辆电动独轮车的大致价格？",
          opts_fr: ["Moins de 800 €", "800 - 1 200 €", "1 200 - 2 000 €", "2 000 - 3 000 €", "Plus de 3 000 €", "Je ne me souviens plus", "Je préfère ne pas répondre"],
          opts_en: ["Under €800", "€800 - 1,200", "€1,200 - 2,000", "€2,000 - 3,000", "Over €3,000", "Don't remember", "Prefer not to say"],
          opts_ru: ["Менее 800 €", "800 – 1 200 €", "1 200 – 2 000 €", "2 000 – 3 000 €", "Более 3 000 €", "Не помню", "Я предпочитаю не отвечать"],
          opts_zh: ["低于800欧元", "800–1200欧元", "1200–2000欧元", "2000–3000欧元", "超过3000欧元", "不记得了", "我不想说"],
        },
        {
          id: "Q7", kind: "single", key: "adoptDelay",
          fr: "Combien de temps après avoir connu les gyroroues en avez-vous acheté une ?",
          en: "How long after discovering EUCs did you buy one?",
          ru: "Через какое время после знакомства с моноколёсами вы купили своё?",
          zh: "在了解到电动独轮车后多久，您购买了一辆？",
          opts_fr: ["Moins d'1 mois", "1-6 mois", "6-12 mois", "1-2 ans", "Plus de 2 ans", "Je ne me souviens plus", "Je préfère ne pas répondre"],
          opts_en: ["Less than 1 month", "1-6 months", "6-12 months", "1-2 years", "Over 2 years", "Don't remember", "Prefer not to say"],
          opts_ru: ["Менее 1 месяца", "1–6 месяцев", "6–12 месяцев", "1–2 года", "Более 2 лет", "Не помню", "Я предпочитаю не отвечать"],
          opts_zh: ["不到1个月", "1–6个月", "6–12个月", "1–2年", "超过2年", "不记得了", "我不想说"],
        },
        {
          id: "Q8", kind: "single", key: "discount",
          fr: "Votre première gyroroue a-t-elle été achetée avec une réduction ?",
          en: "Was your first EUC purchased with a discount?",
          ru: "Было ли ваше первое моноколесо куплено со скидкой?",
          zh: "您的第一辆电动独轮车是否以折扣价购买？",
          opts_fr: ["Oui", "Non", "Je préfère ne pas répondre"],
          opts_en: ["Yes", "No", "Prefer not to say"],
          opts_ru: ["Да", "Нет", "Я предпочитаю не отвечать"],
          opts_zh: ["是", "否", "我不想说"],
        },
        {
          id: "Q9", kind: "single", key: "learningTime",
          fr: "Combien de temps vous a-t-il fallu pour apprendre ?",
          en: "How long did it take to learn?",
          ru: "Сколько времени вам потребовалось, чтобы научиться?",
          zh: "您花了多长时间学会？",
          opts_fr: ["Moins d'1 heure", "1-5 heures", "5-10 heures", "10-20 heures", "Plus de 20 heures", "Je ne me souviens plus", "Je préfère ne pas répondre"],
          opts_en: ["Under 1 hour", "1-5 hours", "5-10 hours", "10-20 hours", "Over 20 hours", "Don't remember", "Prefer not to say"],
          opts_ru: ["Менее 1 часа", "1–5 часов", "5–10 часов", "10–20 часов", "Более 20 часов", "Не помню", "Я предпочитаю не отвечать"],
          opts_zh: ["不到1小时", "1–5小时", "5–10小时", "10–20小时", "超过20小时", "不记得了", "我不想说"],
        },
        {
          id: "Q10", kind: "single", key: "tutorials",
          fr: "Avez-vous utilisé des tutoriels/vidéos pour apprendre ?",
          en: "Did you use tutorials/videos to learn?",
          ru: "Использовали ли вы обучающие видео или уроки для обучения?",
          zh: "您是否使用教程/视频来学习？",
          opts_fr: ["Oui", "Non", "Je préfère ne pas répondre"],
          opts_en: ["Yes", "No", "Prefer not to say"],
          opts_ru: ["Да", "Нет", "Я предпочитаю не отвечать"],
          opts_zh: ["是", "否", "我不想说"],
        },
        {
          id: "Q11", kind: "likert", key: "learningDifficulty",
          fr: "Comment évaluez-vous la difficulté d'apprentissage ?",
          en: "How would you rate the learning difficulty?",
          ru: "Как бы вы оценили сложность обучения?",
          zh: "您如何评价学习难度？",
          ends: "13",
        },
      ],
    },
    {
      id: 3, shows: ["reg", "occ"],
      questions: [
        {
          id: "Q12", kind: "single", key: "weeklyDistance",
          fr: "Quelle distance parcourez-vous chaque semaine ?",
          en: "What distance do you travel weekly?",
          ru: "Какое расстояние вы проезжаете каждую неделю?",
          zh: "您每周骑行多少距离？",
          opts_fr: ["Moins de 10 km", "10-30 km", "30-80 km", "80-200 km", "Plus de 200 km", "Je ne sais pas", "Je préfère ne pas répondre"],
          opts_en: ["Under 10 km", "10-30 km", "30-80 km", "80-200 km", "Over 200 km", "Don't know", "Prefer not to say"],
          opts_ru: ["Менее 10 км", "10–30 км", "30–80 км", "80–200 км", "Более 200 км", "Не знаю", "Я предпочитаю не отвечать"],
          opts_zh: ["不到10公里", "10–30公里", "30–80公里", "80–200公里", "超过200公里", "不知道", "我不想说"],
        },
        {
          id: "Q13", kind: "single", key: "mainUse",
          fr: "Quelle est votre utilisation principale ?",
          en: "What is your main use?",
          ru: "Каково ваше основное использование?",
          zh: "您的主要用途是什么？",
          opts_fr: ["Trajets domicile-travail / école", "Loisirs", "Sport ou balades longues", "Trajets courts (courses, local)", "Autre", "Je préfère ne pas répondre"],
          opts_en: ["Commuting", "Leisure", "Sport or long rides", "Short trips (errands, local)", "Other", "Prefer not to say"],
          opts_ru: ["Поездки на работу / учёбу", "Досуг", "Спорт или длительные поездки", "Короткие поездки (по делам, местные)", "Другое", "Я предпочитаю не отвечать"],
          opts_zh: ["通勤/上学", "休闲", "运动或长途骑行", "短途出行（办事、本地）", "其他", "我不想说"],
        },
        {
          id: "Q14", kind: "single", key: "transportReplace",
          fr: "Quel mode de transport remplace-t-elle le plus souvent ?",
          en: "Which transport mode does it most often replace?",
          ru: "Какой вид транспорта она чаще всего заменяет?",
          zh: "它最常替代哪种交通方式？",
          opts_fr: ["Marche", "Voiture", "Transport public", "Vélo", "Aucun", "Autre", "Je préfère ne pas répondre"],
          opts_en: ["Walking", "Car", "Public transport", "Bike", "None", "Other", "Prefer not to say"],
          opts_ru: ["Ходьба", "Автомобиль", "Общественный транспорт", "Велосипед", "Ничего", "Другое", "Я предпочитаю не отвечать"],
          opts_zh: ["步行", "汽车", "公共交通", "自行车", "无", "其他", "我不想说"],
        },
        {
          id: "Q15", kind: "single", key: "carAccess",
          fr: "Avez-vous un accès régulier à une voiture ?",
          en: "Do you have regular car access?",
          ru: "Имеете ли вы регулярный доступ к автомобилю?",
          zh: "您是否经常使用汽车？",
          opts_fr: ["Oui, je possède une voiture", "Oui, un accès partagé", "Non", "Je préfère ne pas répondre"],
          opts_en: ["Yes, I own one", "Yes, shared access", "No", "Prefer not to say"],
          opts_ru: ["Да, у меня есть автомобиль", "Да, общий доступ", "Нет", "Я предпочитаю не отвечать"],
          opts_zh: ["是，我拥有一辆", "是，共享使用", "否", "我不想说"],
        },
        {
          id: "Q16", kind: "likert-matrix", key: "comparison",
          fr: "Comparée à mon principal moyen de transport, la gyroroue est…",
          en: "Compared to my main transport mode, the EUC is…",
          ru: "По сравнению с моим основным видом транспорта, моноколесо…",
          zh: "与我的主要交通方式相比，电动独轮车…",
          ends: "12",
          rows_fr: ["… plus rapide", "… plus flexible", "… plus pratique", "… plus sûre", "… plus écologique", "… meilleur rapport qualité-prix"],
          rows_en: ["… faster", "… more flexible", "… more convenient", "… safer", "… more eco-friendly", "… better value"],
          rows_ru: ["… быстрее", "… гибче", "… удобнее", "… безопаснее", "… экологичнее", "… выгоднее"],
          rows_zh: ["…更快", "…更灵活", "…更方便", "…更安全", "…更环保", "…更划算"],
        },
      ],
    },
    {
      id: 4, shows: ["reg", "occ", "ex", "curious", "never", "skip"],
      questions: [
        {
          id: "Q17", kind: "likert-matrix", key: "limitingFactors",
          fr: "Dans quelle mesure les facteurs suivants limitent l'usage ou l'adoption ?",
          en: "To what extent do the following factors limit use or adoption?",
          ru: "В какой степени следующие факторы ограничивают использование или принятие?",
          zh: "以下因素在多大程度上限制了使用或采用？",
          ends: "13",
          rows_fr: ["Le prix", "Les difficultés d'apprentissage", "Le niveau de sécurité", "Les contraintes réglementaires", "Le manque d'infrastructures"],
          rows_en: ["Price", "Learning difficulty", "Safety level", "Regulatory constraints", "Lack of infrastructure"],
          rows_ru: ["Цена", "Сложность обучения", "Уровень безопасности", "Нормативные ограничения", "Недостаток инфраструктуры"],
          rows_zh: ["价格", "学习难度", "安全水平", "法规限制", "基础设施不足"],
        },
        {
          id: "Q18", kind: "multi", key: "protections",
          fr: "Quelles protections utilisez-vous quand vous êtes sur la roue ?",
          en: "What protective gear do you use when riding?",
          ru: "Какие средства защиты вы используете при езде?",
          zh: "骑行时您使用哪些防护装备？",
          hint_fr: "Plusieurs réponses possibles", hint_en: "Select all that apply",
          hint_ru: "Выберите все подходящие варианты", hint_zh: "请选择所有适用项",
          opts_fr: ["Casque", "Protège-poignets", "Genouillères", "Veste de protection", "Aucun", "Je préfère ne pas répondre"],
          opts_en: ["Helmet", "Wrist guards", "Knee pads", "Protective jacket", "None", "Prefer not to say"],
          opts_ru: ["Шлем", "Защита запястий", "Наколенники", "Защитная куртка", "Ничего", "Я предпочитаю не отвечать"],
          opts_zh: ["头盔", "护腕", "护膝", "防护夹克", "无", "我不想说"],
        },
        {
          id: "Q19", kind: "single", key: "regulationStatus",
          fr: "Dans votre pays, les gyroroues sont-elles autorisées sur la voie publique ?",
          en: "In your country, are EUCs allowed on public roads?",
          ru: "В вашей стране разрешены ли моноколёса на дорогах общего пользования?",
          zh: "在您的国家，电动独轮车是否允许在公共道路上行驶？",
          opts_fr: ["Oui", "Oui, avec des restrictions", "Non", "Je ne sais pas", "Je préfère ne pas répondre"],
          opts_en: ["Yes", "Yes, with restrictions", "No", "Don't know", "Prefer not to say"],
          opts_ru: ["Да", "Да, с ограничениями", "Нет", "Не знаю", "Я предпочитаю не отвечать"],
          opts_zh: ["是", "是，但有限制", "否", "不知道", "我不想说"],
        },
        {
          id: "Q20", kind: "single", key: "regulationInfluence",
          fr: "Dans quelle mesure la réglementation influence-t-elle votre usage ?",
          en: "To what extent does regulation influence your use?",
          ru: "В какой степени регулирование влияет на ваше использование?",
          zh: "法规在多大程度上影响您的使用？",
          opts_fr: ["Fortement", "Modérément", "Pas du tout", "Je ne sais pas", "Je préfère ne pas répondre"],
          opts_en: ["Strongly", "Moderately", "Not at all", "Don't know", "Prefer not to say"],
          opts_ru: ["Сильно", "Умеренно", "Совсем нет", "Не знаю", "Я предпочитаю не отвечать"],
          opts_zh: ["很大影响", "中等影响", "毫无影响", "不知道", "我不想说"],
        },
        {
          id: "Q21", kind: "single", key: "regulationRenounced",
          fr: "Avez-vous déjà renoncé à choisir une gyroroue en raison de la réglementation ?",
          en: "Have you ever given up on an EUC because of regulation?",
          ru: "Отказывались ли вы когда-либо от моноколеса из-за регулирования?",
          zh: "您是否曾因法规原因放弃选择电动独轮车？",
          opts_fr: ["Oui", "Non", "Je préfère ne pas répondre"],
          opts_en: ["Yes", "No", "Prefer not to say"],
          opts_ru: ["Да", "Нет", "Я предпочитаю не отвечать"],
          opts_zh: ["是", "否", "我不想说"],
        },
      ],
    },
    {
      id: 5, shows: ["reg", "occ", "ex"],
      questions: [
        {
          id: "Q22", kind: "single", key: "socialCircle",
          fr: "Combien de personnes de votre entourage utilisent régulièrement une gyroroue ?",
          en: "How many people in your circle ride regularly?",
          ru: "Сколько человек из вашего окружения регулярно ездят на моноколесе?",
          zh: "您周围有多少人经常骑电动独轮车？",
          opts_fr: ["Aucune", "1-2", "3-5", "Plus de 5", "Je ne sais pas", "Je préfère ne pas répondre"],
          opts_en: ["None", "1-2", "3-5", "More than 5", "Don't know", "Prefer not to say"],
          opts_ru: ["Ни одной", "1–2", "3–5", "Более 5", "Не знаю", "Я предпочитаю не отвечать"],
          opts_zh: ["没有", "1–2人", "3–5人", "超过5人", "不知道", "我不想说"],
        },
        {
          id: "Q23", kind: "single", key: "groupRides",
          fr: "Participez-vous à des sorties collectives ?",
          en: "Do you participate in group rides?",
          ru: "Участвуете ли вы в групповых поездках?",
          zh: "您是否参加集体骑行活动？",
          opts_fr: ["Jamais", "Quelques fois par an", "Au moins une fois par mois", "Je préfère ne pas répondre"],
          opts_en: ["Never", "A few times a year", "At least once a month", "Prefer not to say"],
          opts_ru: ["Никогда", "Несколько раз в год", "Минимум раз в месяц", "Я предпочитаю не отвечать"],
          opts_zh: ["从不", "一年几次", "至少每月一次", "我不想说"],
        },
        {
          id: "Q24", kind: "single", key: "onlineCommunity",
          fr: "Êtes-vous membre d'une communauté en ligne liée aux gyroroues ?",
          en: "Are you a member of an online EUC community?",
          ru: "Являетесь ли вы участником онлайн-сообщества, связанного с моноколёсами?",
          zh: "您是否加入了与电动独轮车相关的在线社区？",
          opts_fr: ["Oui", "Non", "Je préfère ne pas répondre"],
          opts_en: ["Yes", "No", "Prefer not to say"],
          opts_ru: ["Да", "Нет", "Я предпочитаю не отвечать"],
          opts_zh: ["是", "否", "我不想说"],
        },
      ],
    },
    {
      id: 6, shows: ["curious", "never"],
      questions: [
        {
          id: "Q25", kind: "likert-matrix", key: "perception",
          fr: "Si vous deviez utiliser une gyroroue, vous pensez que ce serait…",
          en: "If you were to use an EUC, you think it would be…",
          ru: "Если бы вы использовали моноколесо, вы думаете, оно было бы…",
          zh: "如果您使用电动独轮车，您认为它会…",
          ends: "12",
          rows_fr: ["… difficile à apprendre", "… dangereux", "… utile pour les déplacements quotidiens", "… trop cher"],
          rows_en: ["… hard to learn", "… dangerous", "… useful for daily commuting", "… too expensive"],
          rows_ru: ["… трудным в освоении", "… опасным", "… полезным для ежедневных поездок", "… слишком дорогим"],
          rows_zh: ["…难以学习", "…危险", "…对日常通勤有用", "…太贵"],
        },
        {
          id: "Q26", kind: "single", key: "futureLikelihood",
          fr: "Quelle est la probabilité que vous utilisiez une gyroroue dans le futur ?",
          en: "How likely are you to use an EUC in the future?",
          ru: "Насколько вероятно, что вы будете использовать моноколесо в будущем?",
          zh: "您未来使用电动独轮车的可能性有多大？",
          opts_fr: ["Très improbable", "Improbable", "Neutre", "Probable", "Très probable", "Je préfère ne pas répondre"],
          opts_en: ["Very unlikely", "Unlikely", "Neutral", "Likely", "Very likely", "Prefer not to say"],
          opts_ru: ["Очень маловероятно", "Маловероятно", "Нейтрально", "Вероятно", "Очень вероятно", "Я предпочитаю не отвечать"],
          opts_zh: ["非常不可能", "不太可能", "中立", "可能", "非常可能", "我不想说"],
        },
        {
          id: "Q27", kind: "multi", key: "barriers",
          fr: "Qu'est-ce qui vous empêche d'utiliser une gyroroue ?",
          en: "What prevents you from using an EUC?",
          ru: "Что мешает вам использовать моноколесо?",
          zh: "是什么阻碍了您使用电动独轮车？",
          hint_fr: "Plusieurs réponses possibles", hint_en: "Select all that apply",
          hint_ru: "Выберите все подходящие варианты", hint_zh: "请选择所有适用项",
          opts_fr: ["Trop cher", "Trop difficile à apprendre", "Trop dangereux", "Incertitude juridique", "Manque d'infrastructures", "Manque d'informations", "Je préfère ne pas répondre"],
          opts_en: ["Too expensive", "Too hard to learn", "Too dangerous", "Legal uncertainty", "Lack of infrastructure", "Lack of information", "Prefer not to say"],
          opts_ru: ["Слишком дорого", "Слишком трудно научиться", "Слишком опасно", "Правовая неопределённость", "Недостаток инфраструктуры", "Недостаток информации", "Я предпочитаю не отвечать"],
          opts_zh: ["太贵", "太难学", "太危险", "法律不确定性", "基础设施不足", "信息不足", "我不想说"],
        },
      ],
    },
    {
      id: 7, shows: ["reg", "occ", "ex", "curious", "never", "skip"],
      questions: [
        {
          id: "MCI-H", kind: "likert-matrix", key: "hedonic",
          fr: "Hédonique — plaisir et stimulation",
          en: "Hedonic — pleasure and stimulation",
          ru: "Гедоническое — удовольствие и стимуляция",
          zh: "享乐维度 — 愉悦与刺激",
          ends: "12",
          group_eyebrow_fr: "Dimension hédonique", group_eyebrow_en: "Hedonic dimension",
          group_eyebrow_ru: "Гедоническое измерение", group_eyebrow_zh: "享乐维度",
          rows_fr: ["Essayer de nouvelles technologies est très stimulant", "J'aime tester de nouveaux produits avant les autres", "J'aime être parmi les premiers à adopter des technologies nouvelles"],
          rows_en: ["Trying new tech is very stimulating", "I like testing products before others", "I enjoy being among the first to adopt new tech"],
          rows_ru: ["Пробовать новые технологии очень стимулирует", "Мне нравится тестировать новые продукты раньше других", "Мне нравится быть среди первых, кто осваивает новые технологии"],
          rows_zh: ["尝试新技术非常令人兴奋", "我喜欢比别人先试用新产品", "我喜欢成为最早采用新技术的人之一"],
        },
        {
          id: "MCI-I", kind: "likert-matrix", key: "instrumental",
          fr: "Instrumental — utilité et fiabilité",
          en: "Instrumental — utility and reliability",
          ru: "Инструментальное — полезность и надёжность",
          zh: "工具维度 — 实用性与可靠性",
          ends: "12",
          group_eyebrow_fr: "Dimension instrumentale", group_eyebrow_en: "Instrumental dimension",
          group_eyebrow_ru: "Инструментальное измерение", group_eyebrow_zh: "工具维度",
          rows_fr: ["Je préfère les solutions éprouvées aux nouveautés incertaines", "J'accepte qu'il y ait des risques à essayer de nouvelles technologies", "Je n'adopte que les technologies largement utilisées"],
          rows_en: ["I prefer proven solutions to uncertain new ones", "I accept risks in trying new tech", "I only adopt widely used tech"],
          rows_ru: ["Я предпочитаю проверенные решения неопределённым новинкам", "Я принимаю риски, связанные с опробованием новых технологий", "Я принимаю только широко используемые технологии"],
          rows_zh: ["相比不确定的新事物，我更喜欢经过验证的解决方案", "我接受尝试新技术带来的风险", "我只采用被广泛使用的技术"],
        },
        {
          id: "MCI-S", kind: "likert-matrix", key: "social",
          fr: "Social — influence et communauté",
          en: "Social — influence and community",
          ru: "Социальное — влияние и сообщество",
          zh: "社会维度 — 影响与社区",
          ends: "12",
          group_eyebrow_fr: "Dimension sociale", group_eyebrow_en: "Social dimension",
          group_eyebrow_ru: "Социальное измерение", group_eyebrow_zh: "社会维度",
          rows_fr: ["J'aime discuter des nouvelles technologies avec les autres", "Je suis influencé par les adoptants précoces", "Je me fie souvent à l'expérience des autres", "J'aime faire partie d'une communauté"],
          rows_en: ["I enjoy discussing new tech with others", "I'm influenced by early adopters", "I often rely on others' experience", "I like being part of a community"],
          rows_ru: ["Мне нравится обсуждать новые технологии с другими", "На меня влияют ранние последователи", "Я часто полагаюсь на опыт других", "Мне нравится быть частью сообщества"],
          rows_zh: ["我喜欢与他人讨论新技术", "我受早期采用者的影响", "我经常依赖他人的经验", "我喜欢成为社区的一部分"],
        },
        {
          id: "MCI-Y", kind: "likert-matrix", key: "symbolic",
          fr: "Symbolique — identité et image",
          en: "Symbolic — identity and image",
          ru: "Символическое — идентичность и имидж",
          zh: "象征维度 — 身份与形象",
          ends: "12",
          group_eyebrow_fr: "Dimension symbolique", group_eyebrow_en: "Symbolic dimension",
          group_eyebrow_ru: "Символическое измерение", group_eyebrow_zh: "象征维度",
          rows_fr: ["Je choisis des produits qui reflètent ma personnalité", "Je me soucie de l'image que renvoient les nouveaux produits", "Essayer de nouvelles technologies construit mon identité", "J'apprécie les produits originaux ou uniques"],
          rows_en: ["I choose products that reflect my personality", "I care about the image new products convey", "Trying new tech helps build my identity", "I appreciate original or unique products"],
          rows_ru: ["Я выбираю продукты, которые отражают мою личность", "Меня заботит имидж, который создают новые продукты", "Опробование новых технологий формирует мою идентичность", "Я ценю оригинальные или уникальные продукты"],
          rows_zh: ["我选择能反映我个性的产品", "我在意新产品所传达的形象", "尝试新技术有助于塑造我的身份", "我欣赏原创或独特的产品"],
        },
        {
          id: "MCI-C", kind: "likert-matrix", key: "cognitive",
          fr: "Cognitive — apprentissage et maîtrise",
          en: "Cognitive — learning and mastery",
          ru: "Когнитивное — обучение и мастерство",
          zh: "认知维度 — 学习与掌握",
          ends: "12",
          group_eyebrow_fr: "Dimension cognitive", group_eyebrow_en: "Cognitive dimension",
          group_eyebrow_ru: "Когнитивное измерение", group_eyebrow_zh: "认知维度",
          rows_fr: ["J'aime apprendre des compétences complexes", "Je suis prêt à investir du temps pour maîtriser des technologies complexes", "J'aime les processus d'apprentissage difficiles"],
          rows_en: ["I like learning complex skills", "I'll invest time to master complex tech", "I enjoy difficult learning processes"],
          rows_ru: ["Мне нравится осваивать сложные навыки", "Я готов(а) вложить время в освоение сложных технологий", "Мне нравятся трудные процессы обучения"],
          rows_zh: ["我喜欢学习复杂的技能", "我愿意投入时间掌握复杂的技术", "我享受困难的学习过程"],
        },
      ],
    },
    {
      id: 8, shows: ["reg", "occ", "ex", "curious", "never", "skip"],
      questions: [
        {
          id: "Q28", kind: "number", key: "age",
          fr: "Votre âge", en: "Your age", ru: "Ваш возраст", zh: "您的年龄",
          placeholder_fr: "ans", placeholder_en: "years", placeholder_ru: "лет", placeholder_zh: "岁",
        },
        {
          id: "Q29", kind: "single", key: "gender",
          fr: "Votre genre", en: "Your gender", ru: "Ваш пол", zh: "您的性别",
          opts_fr: ["Homme", "Femme", "Autre", "Je préfère ne pas répondre"],
          opts_en: ["Man", "Woman", "Other", "Prefer not to say"],
          opts_ru: ["Мужчина", "Женщина", "Другое", "Я предпочитаю не отвечать"],
          opts_zh: ["男", "女", "其他", "我不想说"],
        },
        {
          id: "Q30", kind: "text", key: "country",
          fr: "Votre pays", en: "Your country", ru: "Ваша страна", zh: "您的国家",
          placeholder_fr: "Pays", placeholder_en: "Country", placeholder_ru: "Страна", placeholder_zh: "国家",
        },
        {
          id: "Q31", kind: "single", key: "citySize",
          fr: "Taille de la ville où vous vivez",
          en: "Size of the city you live in",
          ru: "Размер города, в котором вы живёте",
          zh: "您居住的城市规模",
          opts_fr: ["Plus d'1 million d'habitants", "200 000 - 1 million", "50 000 - 200 000", "Moins de 50 000", "Campagne", "Je préfère ne pas répondre"],
          opts_en: ["Over 1 million", "200,000 - 1 million", "50,000 - 200,000", "Under 50,000", "Countryside", "Prefer not to say"],
          opts_ru: ["Более 1 миллиона жителей", "200 000 – 1 миллион", "50 000 – 200 000", "Менее 50 000", "Сельская местность", "Я предпочитаю не отвечать"],
          opts_zh: ["超过100万居民", "20万–100万", "5万–20万", "低于5万", "乡村", "我不想说"],
        },
        {
          id: "Q32", kind: "single", key: "occupation",
          fr: "Votre profession", en: "Your occupation", ru: "Ваша профессия", zh: "您的职业",
          opts_fr: ["Étudiant", "Salarié", "Indépendant", "Sans emploi", "Retraité", "Autre", "Je préfère ne pas répondre"],
          opts_en: ["Student", "Employee", "Self-employed", "Unemployed", "Retired", "Other", "Prefer not to say"],
          opts_ru: ["Студент", "Наёмный работник", "Самозанятый", "Безработный", "Пенсионер", "Другое", "Я предпочитаю не отвечать"],
          opts_zh: ["学生", "雇员", "自雇", "无业", "退休", "其他", "我不想说"],
        },
        {
          id: "Q33", kind: "single", key: "income",
          fr: "Votre revenu mensuel approximatif",
          en: "Your approximate monthly income",
          ru: "Ваш примерный ежемесячный доход",
          zh: "您的大致月收入",
          opts_fr: ["Moins de 1 000 €", "1 000 - 2 000 €", "2 000 - 3 000 €", "3 000 - 5 000 €", "Plus de 5 000 €", "Je préfère ne pas répondre"],
          opts_en: ["Under €1,000", "€1,000 - 2,000", "€2,000 - 3,000", "€3,000 - 5,000", "Over €5,000", "Prefer not to say"],
          opts_ru: ["Менее 1 000 €", "1 000 – 2 000 €", "2 000 – 3 000 €", "3 000 – 5 000 €", "Более 5 000 €", "Я предпочитаю не отвечать"],
          opts_zh: ["低于1000欧元", "1000–2000欧元", "2000–3000欧元", "3000–5000欧元", "超过5000欧元", "我不想说"],
        },
      ],
    },
  ],
};

// Helper: compute which parts are shown for a given filter key
export const getActiveParts = function (filterKey) {
  if (!filterKey) return [];
  return SURVEY.parts.filter(p => p.shows.includes(filterKey)).map(p => p.id);
};

// Count total questions in active parts (each likert-matrix counts as 1 q)
export const getTotalQuestions = function (filterKey) {
  const active = getActiveParts(filterKey);
  return SURVEY.parts
    .filter(p => active.includes(p.id))
    .reduce((acc, p) => acc + p.questions.length, 0) + 1; // +1 for Q1
};
